/* AUREX Data Layer — Global Luxury Marketplace Intelligence */

const AUREX = {

  brand: {
    name: 'AUREX',
    tagline: 'Infinite. Elevated. Unmatched.',
    currency: '$',
    version: '∞'
  },

  products: [
    {
      id: 'AX-001',
      name: 'Void Apex Chronograph',
      category: 'Chronometry',
      subcategory: 'Luxury Timepieces',
      price: 12800,
      originalPrice: 18400,
      currency: 'USD',
      gradient: 'linear-gradient(145deg, #0d0d1a 0%, #1a0d2e 40%, #0d1a2e 100%)',
      accentColor: '#D4A843',
      badge: 'Only 7 Left',
      badgeType: 'urgent',
      rating: 4.97,
      reviews: 1247,
      tag: 'Handcrafted in Geneva',
      description: 'Forged from meteorite carbon fiber. 72-hour power reserve. Zero gravity tested.',
      sold: 93,
      emoji: '⌚',
    },
    {
      id: 'AX-002',
      name: 'Neural Silk Evening Gown',
      category: 'Haute Couture',
      subcategory: 'Evening Wear',
      price: 8950,
      originalPrice: 8950,
      currency: 'USD',
      gradient: 'linear-gradient(145deg, #1a0a1a 0%, #2e0d2e 40%, #1a0a2e 100%)',
      accentColor: '#C084FC',
      badge: 'New Arrival',
      badgeType: 'new',
      rating: 4.95,
      reviews: 432,
      tag: 'Zero Carbon Luxury',
      description: 'Woven from lab-grown silk threads with embedded micro-luminescence.',
      sold: 45,
      emoji: '👗',
    },
    {
      id: 'AX-003',
      name: 'Obsidian Apex Sneaker',
      category: 'Footwear',
      subcategory: 'Limited Edition',
      price: 2400,
      originalPrice: 3200,
      currency: 'USD',
      gradient: 'linear-gradient(145deg, #0a0a0a 0%, #1a1a1a 40%, #0a0d1a 100%)',
      accentColor: '#F2C95C',
      badge: 'Flash Deal',
      badgeType: 'flash',
      rating: 4.99,
      reviews: 8934,
      tag: 'Self-Cleaning Nano Tech',
      description: 'Carbon fiber sole. Responsive foam matrix. 100-year durability guarantee.',
      sold: 78,
      emoji: '👟',
    },
    {
      id: 'AX-004',
      name: 'Quantum Diamond Pendant',
      category: 'Jewelry',
      subcategory: 'Fine Jewelry',
      price: 24600,
      originalPrice: 24600,
      currency: 'USD',
      gradient: 'linear-gradient(145deg, #0d1a0d 0%, #0d2e1a 40%, #0a1a1a 100%)',
      accentColor: '#34D399',
      badge: 'One of Kind',
      badgeType: 'exclusive',
      rating: 5.00,
      reviews: 89,
      tag: 'Lab Quantum Grown',
      description: 'D-grade flawless diamond grown in quantum pressure chambers. Ethically infinite.',
      sold: 100,
      emoji: '💎',
    },
    {
      id: 'AX-005',
      name: 'Nomad Apex Travel Set',
      category: 'Accessories',
      subcategory: 'Travel Luxury',
      price: 3800,
      originalPrice: 5200,
      currency: 'USD',
      gradient: 'linear-gradient(145deg, #1a0d0a 0%, #2e1a0d 40%, #1a1a0d 100%)',
      accentColor: '#FB923C',
      badge: 'Best Seller',
      badgeType: 'popular',
      rating: 4.93,
      reviews: 3847,
      tag: 'Aerospace Grade',
      description: 'Titanium frame, self-organizing interior. RFID shield. Works in 174 countries.',
      sold: 67,
      emoji: '🧳',
    },
    {
      id: 'AX-006',
      name: 'Aurora Noir Parfum',
      category: 'Fragrance',
      subcategory: 'Luxury Scents',
      price: 1200,
      originalPrice: 1200,
      currency: 'USD',
      gradient: 'linear-gradient(145deg, #0d0a1a 0%, #1a0d2e 40%, #2e0d1a 100%)',
      accentColor: '#F472B6',
      badge: 'Signature',
      badgeType: 'signature',
      rating: 4.88,
      reviews: 2341,
      tag: 'Arabian Oud Reserve',
      description: '47-hour lasting power. Aged 12 years. 14 impossible-to-source ingredients.',
      sold: 55,
      emoji: '🌺',
    },
  ],

  flashDeals: [
    {
      id: 'FD-001',
      name: 'Stealth Carbon Watch',
      originalPrice: 9400,
      flashPrice: 4200,
      discount: 55,
      endsIn: 3 * 3600 + 24 * 60 + 17,
      claimed: 84,
      total: 100,
      gradient: 'linear-gradient(145deg, #0a0a14 0%, #14102e 100%)',
      emoji: '⌚',
    },
    {
      id: 'FD-002',
      name: 'Midnight Mink Coat',
      originalPrice: 18000,
      flashPrice: 7200,
      discount: 60,
      endsIn: 1 * 3600 + 47 * 60 + 33,
      claimed: 97,
      total: 20,
      gradient: 'linear-gradient(145deg, #140a14 0%, #2e102e 100%)',
      emoji: '🧥',
    },
    {
      id: 'FD-003',
      name: 'Gold Titanium Bracelet',
      originalPrice: 6800,
      flashPrice: 2900,
      discount: 57,
      endsIn: 6 * 3600 + 12 * 60 + 44,
      claimed: 52,
      total: 50,
      gradient: 'linear-gradient(145deg, #141000 0%, #2e2400 100%)',
      emoji: '📿',
    },
    {
      id: 'FD-004',
      name: 'Gravity X Sunglasses',
      originalPrice: 2400,
      flashPrice: 890,
      discount: 63,
      endsIn: 0 * 3600 + 58 * 60 + 9,
      claimed: 99,
      total: 30,
      gradient: 'linear-gradient(145deg, #001414 0%, #00242e 100%)',
      emoji: '🕶️',
    },
  ],

  worldCities: [
    { name: 'New York', lat: 40.71, lng: -74.00, orders: 847, flag: '🇺🇸' },
    { name: 'London', lat: 51.51, lng: -0.13, orders: 634, flag: '🇬🇧' },
    { name: 'Tokyo', lat: 35.69, lng: 139.69, orders: 1203, flag: '🇯🇵' },
    { name: 'Dubai', lat: 25.20, lng: 55.27, orders: 923, flag: '🇦🇪' },
    { name: 'Paris', lat: 48.86, lng: 2.35, orders: 512, flag: '🇫🇷' },
    { name: 'Singapore', lat: 1.35, lng: 103.82, orders: 788, flag: '🇸🇬' },
    { name: 'Sydney', lat: -33.87, lng: 151.21, orders: 341, flag: '🇦🇺' },
    { name: 'São Paulo', lat: -23.55, lng: -46.63, orders: 287, flag: '🇧🇷' },
    { name: 'Mumbai', lat: 19.08, lng: 72.88, orders: 445, flag: '🇮🇳' },
    { name: 'Shanghai', lat: 31.22, lng: 121.47, orders: 956, flag: '🇨🇳' },
    { name: 'Riyadh', lat: 24.69, lng: 46.72, orders: 678, flag: '🇸🇦' },
    { name: 'Berlin', lat: 52.52, lng: 13.41, orders: 389, flag: '🇩🇪' },
    { name: 'Toronto', lat: 43.65, lng: -79.38, orders: 298, flag: '🇨🇦' },
    { name: 'Seoul', lat: 37.57, lng: 126.98, orders: 712, flag: '🇰🇷' },
    { name: 'Milan', lat: 45.46, lng: 9.19, orders: 434, flag: '🇮🇹' },
  ],

  liveOrders: [
    { name: 'Yuki T.', city: 'Tokyo', product: 'Void Apex Chronograph', amount: 12800, flag: '🇯🇵', time: '2s ago' },
    { name: 'Khalid A.', city: 'Dubai', product: 'Quantum Diamond Pendant', amount: 24600, flag: '🇦🇪', time: '8s ago' },
    { name: 'Sophie M.', city: 'Paris', product: 'Neural Silk Gown', amount: 8950, flag: '🇫🇷', time: '12s ago' },
    { name: 'Marcus J.', city: 'New York', product: 'Obsidian Apex Sneaker', amount: 2400, flag: '🇺🇸', time: '19s ago' },
    { name: 'Priya K.', city: 'Singapore', product: 'Aurora Noir Parfum', amount: 1200, flag: '🇸🇬', time: '24s ago' },
    { name: 'Liu W.', city: 'Shanghai', product: 'Nomad Apex Travel Set', amount: 3800, flag: '🇨🇳', time: '31s ago' },
    { name: 'Amira S.', city: 'Riyadh', product: 'Gold Titanium Bracelet', amount: 2900, flag: '🇸🇦', time: '37s ago' },
    { name: 'Finn L.', city: 'London', product: 'Stealth Carbon Watch', amount: 4200, flag: '🇬🇧', time: '44s ago' },
    { name: 'Isabella R.', city: 'Milan', product: 'Midnight Mink Coat', amount: 7200, flag: '🇮🇹', time: '52s ago' },
    { name: 'Jae-won P.', city: 'Seoul', product: 'Gravity X Sunglasses', amount: 890, flag: '🇰🇷', time: '1m ago' },
    { name: 'Omar F.', city: 'Cairo', product: 'Void Apex Chronograph', amount: 12800, flag: '🇪🇬', time: '1m ago' },
    { name: 'Nina B.', city: 'Berlin', product: 'Neural Silk Gown', amount: 8950, flag: '🇩🇪', time: '1m ago' },
  ],

  achievements: [
    { id: 'first-buy', icon: '🏆', name: 'First Claim', desc: 'Made your first acquisition', unlocked: true, xp: 100 },
    { id: 'gold-tier', icon: '⚜️', name: 'Gold Ascent', desc: 'Reached Gold Tier status', unlocked: true, xp: 500 },
    { id: 'collector', icon: '💎', name: 'The Collector', desc: 'Owned 10 AUREX pieces', unlocked: true, xp: 1000 },
    { id: 'flash-hunter', icon: '⚡', name: 'Flash Hunter', desc: 'Claimed 5 flash deals', unlocked: false, xp: 750 },
    { id: 'globe-trekker', icon: '🌍', name: 'Globe Trekker', desc: 'Ordered from 3 continents', unlocked: false, xp: 1200 },
    { id: 'legendary', icon: '👑', name: 'Legendary Status', desc: 'Reach Platinum Infinity tier', unlocked: false, xp: 5000 },
  ],

  leaderboard: [
    { rank: 1, name: 'Khalid A.', city: 'Dubai', tier: 'Platinum ∞', xp: 94720, flag: '🇦🇪' },
    { rank: 2, name: 'Yuki T.', city: 'Tokyo', tier: 'Platinum ∞', xp: 87340, flag: '🇯🇵' },
    { rank: 3, name: 'Sofia C.', city: 'Milan', tier: 'Gold Elite', xp: 63480, flag: '🇮🇹' },
    { rank: 4, name: 'Marcus V.', city: 'New York', tier: 'Gold Elite', xp: 58290, flag: '🇺🇸' },
    { rank: 5, name: 'Amira N.', city: 'Riyadh', tier: 'Gold', xp: 41760, flag: '🇸🇦' },
  ],

  collections: [
    { id: 'col-1', name: 'Void Series', desc: 'Where darkness meets precision', count: 47, gradient: 'linear-gradient(135deg, #0a0a1a 0%, #1a1040 100%)', accent: '#7C3AED' },
    { id: 'col-2', name: 'Solar Apex', desc: 'Harnessing the power of light', count: 31, gradient: 'linear-gradient(135deg, #1a0a00 0%, #3d1e00 100%)', accent: '#F59E0B' },
    { id: 'col-3', name: 'Chronos Edit', desc: 'Timeless beyond measure', count: 58, gradient: 'linear-gradient(135deg, #000a14 0%, #001a2e 100%)', accent: '#0EA5E9' },
    { id: 'col-4', name: 'Terra Nova', desc: 'Crafted from Earth\'s rarest', count: 24, gradient: 'linear-gradient(135deg, #001400 0%, #002e10 100%)', accent: '#10B981' },
    { id: 'col-5', name: 'Nebula Couture', desc: 'Fashion from another dimension', count: 39, gradient: 'linear-gradient(135deg, #140014 0%, #2e0040 100%)', accent: '#EC4899' },
    { id: 'col-6', name: 'Phantom Tech', desc: 'Intelligence woven into fabric', count: 22, gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 100%)', accent: '#D4A843' },
  ],

  membershipTiers: [
    {
      name: 'Obsidian',
      price: 'Free',
      icon: '⬛',
      color: '#4B5563',
      benefits: [
        'Access to AUREX marketplace',
        'Standard delivery (5-7 days)',
        'Basic member rewards',
        'Monthly newsletter',
      ]
    },
    {
      name: 'Gold',
      price: '$199/yr',
      icon: '🌟',
      color: '#D4A843',
      featured: true,
      benefits: [
        'Early access to flash deals',
        'Priority delivery (2-3 days)',
        '3x reward multiplier',
        'Exclusive Gold collections',
        'Personal style concierge',
        'Free authentication service',
      ]
    },
    {
      name: 'Platinum ∞',
      price: '$999/yr',
      icon: '♾️',
      color: '#E8E4DC',
      benefits: [
        'Pre-launch exclusive access',
        'Same-day delivery worldwide',
        '10x reward multiplier',
        'All collections unlocked',
        'Dedicated personal shopper',
        'Private vault storage',
        'Annual collector event invite',
        'White-glove returns forever',
      ]
    }
  ]
};

window.AUREX = AUREX;
